### ISSUE TITLE
Issue with ACL for the Graph widget

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-graph-monitoring#3]
---

Author Name: **ROBIN matthieu** (ROBIN matthieu)
Original Redmine Issue: 4614, https://forge.centreon.com/issues/4614
Original Date: 2013-07-09

---

Hello,
I have configured some users with all access on the "Custom View", "view" and "All hosts". If they add a widget with the status, it works fine. But if they add a Graph, they cannot have a message error: " you're not allowed to reach this graph". And if they go to View, they can reach the graph. 
Any idea?

thanks in advance.

**Comment by julienmathis** [comment]
To be test
