### ISSUE TITLE
New contact can't see graph

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-graph-monitoring#5]
---

Author Name: **Stephane Duret** (Stephane Duret)
Original Redmine Issue: 6006, https://forge.centreon.com/issues/6006
Original Date: 2014-12-01

---

Hello,

I have an issue if I share a view (with widget graph) with a user.
The view is shared with a contact group.

So, if I add a new contact in this contact group, he doesn't see the graph but a message "Select ressource first".

The workaround is to delete the contact group in the "share view" options and save that.
Now I can add the same contact group and the user will see the graph.

Regards,

**Comment by julienmathis** [comment]
To be test !
