### ISSUE TITLE
Height resize of graph widget

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-graph-monitoring#8]
---

Author Name: **maxime longuet** (maxime longuet)
Original Redmine Issue: 6414, https://forge.centreon.com/issues/6414
Original Date: 2015-05-29

---

Hy,

On this version the widget don't resize height of iFrame. I put in line 154 :

parent.iResize(window.name, h);

This correction are present on CES Server ;)

Thanks

**Comment by rk4an** [comment]
Hi,

The bug is still present on the version 1.1.0 of the plugin available on the main page: https://download.centreon.com/

Putting parent.iResize(window.name, h); in ligne 154 of file inde.php fix that problem

Thanks :)

**Comment by Moujimouja** [comment]
Hello,

You're right, package are not correct on download.centreon.com. Thanks for your feedback.

It's been corrected here dd3fbb0cce18de3f976b3b0ea72dfbde2493aeec and the master has been merged with the 1.1.x branch so the code are the same.

We 're going to test it and re-generate package for download.centreon.com.
